### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by nasihui** [MarbledNull/Marbleds-Core#4]
I really love your mod but can you tell me how rare is the titanium ore? like is it more rare than netherite or more rare than diamond and how much more rare than said ore (give reference ore pls)

**Comment by MelodicCougar7** [comment]
It is slightly more common than deep slate diamond as of the current release. It's most common in the deep slate layer and the easier way to obtain it is go spelunking in a large deep slate cavern.

Marbled has said that he wants to tweak generation for balance, so expect this information to change.

**Comment by MarbledNull** [comment]
Don't create issues just for a question. Join the Discord if you have any questions or concerns. But yes, what MelodicCougar7 said.

**Comment by nasihui** [comment]
thats common for such op ore

**Comment by MarbledNull** [comment]
if you didn't read the last part, it's being tweaked for balance. wont be as OP
